### ISSUE TITLE
Improve the perfromace of tile canvas

### ISSUE THREAD

**Issue by CaviarChen** [CaviarChen/fog-machine#7]
- [x] have a way to figure out outdated canvas when the fow data is modified. #9
- [ ] have a faster way to check whether a canvas only contains fog.
- [x] for fog only canvas, a 1x1 `HTMLCanvasElement` should be enough.  #37 
- [x] for all fog only canvases, share the same canvas (require copy on write when they have data later) #37 
- [x] for all fog only canvases, share the same texture2d cache. #37 
- [ ] increase the tilecanvas cache. Maybe consider having another canvas cache.
